---
- name: creating a sample
  hosts: all
  tasks:
  - name: creating user
    user:
      name: viggy
      state: present
  - name: installing packages
    yum:
      name: httpd
      state: present    
